import { expect, test } from "@playwright/test";
import { readDemoRows } from "./test-environment";

test("timezone search filters on a phone, supports keyboard and touch selection, and saves the choice", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 320, height: 700 });
  await page.goto("/demo");
  await page.getByRole("button", { name: "Start demo", exact: true }).click();
  await expect(page).toHaveURL(/\/log$/);
  const owner = (await (await page.request.get("/api/financial-history")).json()).entries[0].userId;
  await page.goto("/settings");
  await page.getByLabel("Edit pay", { exact: true }).click();
  const sheet = page.getByRole("dialog", { name: "Pay", exact: true });
  const field = sheet.getByRole("combobox", { name: "Timezone", exact: true });
  await expect(field).toHaveValue("America/New_York");
  await field.fill("Ameri");
  const list = sheet.getByRole("listbox", { name: "Timezones", exact: true });
  await expect(list).toBeVisible();
  const choices = await list.getByRole("option").allTextContents();
  expect(choices.length).toBeGreaterThan(50);
  expect(choices.every(text => text.startsWith("America/"))).toBe(true);
  const box = (await list.boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(321);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await sheet.getByRole("button", { name: "Clear timezone search", exact: true }).tap();
  await expect(field).toHaveValue("");
  expect(await list.getByRole("option").count()).toBeGreaterThan(400);
  await field.fill("New York");
  await expect(list.getByRole("option")).toHaveCount(1);
  await list.getByRole("option", { name: "America/New_York", exact: true }).tap();
  await expect(list).not.toBeVisible();
  await expect(field).toHaveValue("America/New_York");
  await field.fill("Made up zone");
  await expect(sheet.getByRole("status")).toHaveText("No matches. Try a city, like Chicago.");
  await field.press("Escape");
  await expect(sheet).toBeVisible();
  await expect(field).toHaveValue("America/New_York");
  await field.fill("Tokyo");
  await field.press("ArrowDown");
  await expect(field).toHaveAttribute("aria-activedescendant", /option-0$/);
  await field.press("Enter");
  await expect(list).not.toBeVisible();
  await expect(field).toHaveValue("Asia/Tokyo");
  await sheet.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(sheet).not.toBeVisible();
  await page.reload();
  await page.getByLabel("Edit pay", { exact: true }).click();
  await expect(field).toHaveValue("Asia/Tokyo");
  expect(await readDemoRows(async client => (await client.query("SELECT timezone FROM settings WHERE user_id=$1", [owner])).rows[0].timezone)).toBe("Asia/Tokyo");
  expect(errors).toEqual([]);
});
